# Generated by Django 2.2 on 2020-08-30 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
    ]
