# Generated by Django 2.2 on 2020-08-30 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_comment_comment_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_count',
        ),
    ]
